import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  headerLeft: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerTitle: { flexShrink: 1, fontSize: 19, fontWeight: '800', letterSpacing: -0.3 },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexShrink: 0,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  addBtnTxt: { fontSize: 12, fontWeight: '700', flexShrink: 1 },
  tabBar: {
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 16,
    marginTop: 12,
    padding: 6,
    borderRadius: 16,
    borderWidth: 1,
  },
  tabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  tabTxt: { fontSize: 11.5, fontWeight: '800', flexShrink: 1 },
  filterBar: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    marginBottom: 10,
    gap: 10,
  },
  filterBarLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 0.7, textTransform: 'uppercase' },
  sortRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sortChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  capacityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  capacityInput: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 9,
    height: 34,
    minWidth: 92,
    flex: 1,
  },
  capacityPrefix: { fontSize: 10.5, fontWeight: '800' },
  capacityTextInput: { fontSize: 13, minWidth: 36, paddingVertical: 0, flex: 1 },
  summaryRow: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  summaryCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 90,
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 14,
    borderWidth: 1.5,
  },
  summaryEmoji: { fontSize: 18, marginBottom: 4 },
  summaryValue: { fontSize: 20, fontWeight: '900', lineHeight: 24 },
  summaryLabel: { fontSize: 9.5, fontWeight: '700', marginTop: 2, textAlign: 'center' },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 12,
  },
  searchInput: { flex: 1, fontSize: 14 },
  resultsInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  resultsCount: { fontSize: 12, fontWeight: '600' },
  clearTxt: { fontSize: 12, fontWeight: '700' },
  envCard: {
    borderRadius: 16,
    borderWidth: 1.5,
    borderLeftWidth: 4,
    overflow: 'hidden',
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  cardTop: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
  cardIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardInfo: { flex: 1 },
  cardName: { fontSize: 15, fontWeight: '800', marginBottom: 4 },
  cardMeta: { flexDirection: 'row', alignItems: 'center', gap: 4, flexWrap: 'wrap' },
  cardMetaTxt: { fontSize: 11.5 },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusTxt: { fontSize: 10, fontWeight: '800' },
  metricsRow: { flexDirection: 'row', borderTopWidth: 1 },
  metricCell: { flex: 1, alignItems: 'center', paddingVertical: 10, gap: 2 },
  metricIcon: { fontSize: 15 },
  metricValue: { fontSize: 12.5, fontWeight: '800', lineHeight: 17 },
  metricLabel: { fontSize: 8.5, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.25 },
  cardActions: { flexDirection: 'row', borderTopWidth: 1 },
  editBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 11,
    borderRightWidth: 1,
  },
  editBtnTxt: { fontSize: 13, fontWeight: '700' },
  deleteBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 11 },
  deleteBtnTxt: { fontSize: 13, fontWeight: '700' },
  empty: {
    alignItems: 'center',
    paddingTop: 38,
    paddingBottom: 32,
    gap: 10,
    borderRadius: 16,
  },
  emptyIcon: { fontSize: 52 },
  emptyTitle: { fontSize: 17, fontWeight: '800', textAlign: 'center' },
  emptySub: { fontSize: 13, lineHeight: 18, textAlign: 'center', paddingHorizontal: 24, marginTop: -4 },
  emptyBtn: { borderRadius: 12, paddingHorizontal: 20, paddingVertical: 11, marginTop: 6 },
  emptyBtnTxt: { fontSize: 14, fontWeight: '700' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  deleteMsg: { fontSize: 14, lineHeight: 20, textAlign: 'center' },
})
