import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: 20, paddingTop: 52, paddingBottom: 18, borderBottomWidth: 0,
    shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 12, shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  headerTitle: { fontSize: 24, fontWeight: '700', letterSpacing: -0.8 },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 28 },
  card: {
    borderRadius: 24, borderWidth: 1, marginBottom: 18, overflow: 'hidden',
    paddingHorizontal: 16, paddingVertical: 15,
    shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  cardTitle: { fontSize: 16, fontWeight: '700', letterSpacing: -0.25 },
  cardDesc: { fontSize: 12, marginBottom: 10, opacity: 0.8 },
  row: {
    flexDirection: 'row', alignItems: 'center',
    paddingVertical: 12, paddingHorizontal: 8, borderRadius: 14,
  },
  rowLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1, marginRight: 8 },
  rowLabel: { fontSize: 14, flex: 1, fontWeight: '600' },
  rowValue: { fontSize: 13, flexShrink: 0, maxWidth: 140, textAlign: 'right', opacity: 0.9 },
  toggle: { width: 50, height: 29, borderRadius: 15, padding: 3, justifyContent: 'center', alignItems: 'flex-start' },
  toggleCircle: { width: 23, height: 23, borderRadius: 12, backgroundColor: '#fff', shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 3 },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 18, borderWidth: 1 },
  chipLabel: { fontSize: 12, fontWeight: '700' },
  timezoneWrap: { marginTop: 12, gap: 8 },
  timezoneLabel: { fontSize: 13, marginBottom: 4 },
  input: { borderRadius: 12, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 11, fontSize: 15, marginBottom: 12 },
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 18 },
  langOption: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 14, paddingVertical: 12, borderRadius: 12, marginBottom: 6,
  },
  langOptionRow: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  langFlag: { fontSize: 18 },
  langOptionText: { fontSize: 15, fontWeight: '600' },
  modalText: { fontSize: 14, lineHeight: 20, textAlign: 'center', marginBottom: 12 },
  dateFormatModalContent: { paddingTop: 8, paddingBottom: 6 },
  dateFormatSubtitle: { fontSize: 13, marginBottom: 16, opacity: 0.9 },
  dateFormatGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  dateFormatOption: {
    width: '48%',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 72,
    justifyContent: 'center',
  },
  dateFormatOptionLabel: { fontSize: 15, fontWeight: '700', marginBottom: 4 },
  dateFormatOptionSample: { fontSize: 13 },
  dateFormatPreviewBox: {
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateFormatPreviewLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 0.5 },
  dateFormatPreviewValue: { fontSize: 22, fontWeight: '700', letterSpacing: -0.8 },
  dateFormatCancelButton: { flex: 1, borderRadius: 12, minHeight: 42 },
  dateFormatSaveButton: { flex: 1, borderRadius: 12, minHeight: 42 },
  dateFormatCancelText: { fontWeight: '700' },
  dateFormatSaveText: { fontWeight: '700' },
  helpItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 14 },
  helpIcon: { fontSize: 16, marginTop: 2 },
  helpLabel: { fontSize: 13, fontWeight: '600', marginBottom: 2 },
  helpValue: { fontSize: 13 },
  helpQuestion: { fontSize: 14, fontWeight: '600', marginBottom: 4 },
  helpAnswer: { fontSize: 13, lineHeight: 18 },
  helpText: { fontSize: 14, lineHeight: 20, marginBottom: 12 },
  helpSection: { marginBottom: 14 },
  helpSectionTitle: { fontSize: 14, fontWeight: '700', marginBottom: 6 },
  helpListItem: { fontSize: 13, lineHeight: 19 },
  versionDesc: { fontSize: 15, fontWeight: '600' },
  versionDate: { fontSize: 12 },
})
